server:
  port: 8888
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/rms?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
  mvc:
    pathmatch:
      # swagger 访问使用
      matching-strategy: ant_path_matcher